[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"
targetPort = 3000
port = 8888

[images]
  remote_images = ["https://cdn.bckstg.app/.*"]

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"
